name: tests
on: [push]
jobs:
  test:
    runs-on: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.7.0'
      - run: npm install
      - run: node index.js