name: tests
on: [push]
jobs:
  test:
    strategy:
      matrix:
        platform: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.platform }}
    name: Test on ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.7.0'
      - run: npm install
      - run: node index.js